### ISSUE TITLE
n_segement and segment_length while training and evaluation

### ISSUE THREAD

**Issue by MohamedAfham** [md-mohaiminul/ViS4mer#3]
Hi, Thanks for the amazing work.

I have a question. It seems in your code you have used `n_segment = 512` and `segment_length = 32` while training and `n_segment = 64` and `segment_length = 32` while evaluation for BREAKFAST dataset. Is it a hyper parameter you investigated or are you following any existing approaches for fair comparison ? (I didn't see anything of that kind for breakfast dataset in the paper.)

Also, in the paper you mentioned, you used VideoGraph [1] for splitting breakfast dataset. However, they've used `n_segment = 64` and `segment_length = 8` in their approach. Can you please give me a clarification ?

Thanks in Advance and again thanks for the great work !

[1] Hussein, N., Gavves, E., Smeulders, A.W.: Videograph: Recognizing minutes-long human activities in videos. arXiv preprint arXiv:1905.05143 (2019)

**Comment by md-mohaiminul** [comment]
Hi,
Thanks for reaching out. I tried to follow the VideoGraph as closely as possible. In VideoGraph codebase, authors use random sampling during training and uniform sampling during testing. Particularly, they randomly sample frames before each training epoch and extract features. As you can imagine this will take a lot of time to train the model. Therefore, authors also suggest an alternative approach, where you can extract features for more segments (e.g., 1024), and randomly sample from the pre-extracted features during training. However, I extracted features for 512 segments instead of 1024 during training, you can also try 1024 which should be even better. 

Here is the explanation from the author of VideoGraph ( and Timeception):
https://github.com/noureldien/timeception/issues/17

Unfortunately, links for VideoGraph is not working but they used same approach for Timeception and VideoGraph.
